version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 3
    versioning-strategy: lockfile-only
    groups:
      angular:
        patterns:
          - '@angular*'
      fullcalendar:
        patterns:
          - '@fullcalendar*'
    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@openproject/primer-view-components"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 3
    versioning-strategy: lockfile-only
    groups:
      aws-gems:
        patterns:
          - "aws-*"
    ignore:
      - dependency-name: "openproject-primer_view_components"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 3
