name: rubocop

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  rubocop:
    name: rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Run Rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          github_token: ${{ secrets.github_token }}
          rubocop_version: gemfile
          rubocop_extensions: >
            rubocop-capybara:gemfile
            rubocop-factory_bot:gemfile
            rubocop-openproject:gemfile
            rubocop-performance:gemfile
            rubocop-rails:gemfile
            rubocop-rspec:gemfile
            rubocop-rspec_rails:gemfile
          reporter: github-pr-check
          only_changed: true
      - name: Install erb_lint
        run: gem install -N erb_lint erblint-github
      - name: Run erb-lint
        uses: tk0miya/action-erblint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          fail_on_error: true
