name: "Frontend test suite"

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - release/*
    paths:
      - '**/frontend/**/*.ts'
      - '**/frontend/**/*.js'
      - '**/frontend/**/*.json'

  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '**/frontend/**/*.ts'
      - '**/frontend/**/*.js'
      - '**/frontend/**/*.json'

permissions:
  contents: read

defaults:
  run:
    working-directory: ./frontend

jobs:
  units:
    name: Units
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v4
        with:
          node-version: '22.15'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        id: npm-i
        run: npm i

      - name: Register plugins
        id: npm-run-ci-plugins-register-frontend
        run: npm run ci:plugins:register_frontend

      - name: Test (Angular)
        id: npm-test
        run: npm test -- --code-coverage
